[project]
name = 'link-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Subscription-Pool-escrow]
path = 'contracts/Subscription-Pool-escrow.clar'
clarity_version = 3
epoch = 3.0

[contracts.acces-control]
path = 'contracts/acces-control.clar'
clarity_version = 1
epoch = 2.05

[contracts.dao-governance]
path = 'contracts/dao-governance.clar'
clarity_version = 3
epoch = 3.0

[contracts.fractional-payment]
path = 'contracts/fractional-payment.clar'
clarity_version = 3
epoch = 3.0

[contracts.multi-service_pooling]
path = 'contracts/multi-service_pooling.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
